import XCTest
@testable import habitOS_mobile

@MainActor
final class DashboardViewModelTests: XCTestCase {

    private var mockAuth: MockAuthRepository!
    private var mockDiet: MockDietRepository!
    private var mockTask: MockTaskRepository!
    private var mockChat: MockChatRepository!
    private var mockJournal: MockJournalRepository!

    override func setUp() {
        super.setUp()
        mockAuth = MockAuthRepository()
        mockDiet = MockDietRepository()
        mockTask = MockTaskRepository()
        mockChat = MockChatRepository()
        mockJournal = MockJournalRepository()
    }

    private func makeSUT() -> DashboardViewModel {
        DashboardViewModel(
            authRepo: mockAuth,
            dietRepo: mockDiet,
            taskRepo: mockTask,
            chatRepo: mockChat,
            journalRepo: mockJournal
        )
    }

    // MARK: - Daily Progress

    func testDailyProgressEmpty() {
        let sut = makeSUT()
        XCTAssertEqual(sut.dailyProgress, 0)
    }

    func testDailyProgressCalculation() {
        let sut = makeSUT()
        let now = Date()
        sut.dailyTasks = [
            DailyTaskItem(id: UUID(), userId: UUID(), taskDate: now, title: "Task 1", category: nil, isCompleted: true, completedAt: now, sortOrder: 0, autoGenerated: false, source: "user", createdAt: now),
            DailyTaskItem(id: UUID(), userId: UUID(), taskDate: now, title: "Task 2", category: nil, isCompleted: true, completedAt: now, sortOrder: 1, autoGenerated: false, source: "user", createdAt: now),
            DailyTaskItem(id: UUID(), userId: UUID(), taskDate: now, title: "Task 3", category: nil, isCompleted: false, completedAt: nil, sortOrder: 2, autoGenerated: false, source: "user", createdAt: now),
        ]
        XCTAssertEqual(sut.dailyProgress, 2.0 / 3.0, accuracy: 0.001)
        XCTAssertEqual(sut.completedTasksCount, 2)
        XCTAssertEqual(sut.totalTasksCount, 3)
    }

    func testDailyProgressAllComplete() {
        let sut = makeSUT()
        let now = Date()
        sut.dailyTasks = [
            DailyTaskItem(id: UUID(), userId: UUID(), taskDate: now, title: "Task 1", category: nil, isCompleted: true, completedAt: now, sortOrder: 0, autoGenerated: false, source: "user", createdAt: now),
        ]
        XCTAssertEqual(sut.dailyProgress, 1.0)
    }

    // MARK: - Load Dashboard (Demo mode)

    func testLoadDashboardNilUserLoadsDemo() async {
        let sut = makeSUT()
        await sut.loadDashboard(user: nil, isDemo: true)

        XCTAssertFalse(sut.isLoading)
        XCTAssertFalse(sut.dailyTasks.isEmpty, "Demo mode should populate tasks")
        XCTAssertNotNil(sut.user, "Demo mode should set a demo user")
    }

    // MARK: - Load Dashboard (Real user)

    func testLoadDashboardWithUserFetchesTasks() async {
        let userId = UUID()
        let testUser = makeTestUser(id: userId)
        let now = Date()

        mockTask.tasks = [
            DailyTaskItem(id: UUID(), userId: userId, taskDate: now, title: "Agua", category: "hydration", isCompleted: false, completedAt: nil, sortOrder: 0, autoGenerated: true, source: "plan", createdAt: now),
        ]

        let sut = makeSUT()
        await sut.loadDashboard(user: testUser)

        XCTAssertFalse(sut.isLoading)
        XCTAssertEqual(sut.dailyTasks.count, 1)
        XCTAssertEqual(sut.dailyTasks.first?.title, "Agua")
        XCTAssertNil(sut.errorMessage)
    }

    func testLoadDashboardWithUserFetchesJournalWater() async {
        let userId = UUID()
        let testUser = makeTestUser(id: userId)
        let now = Date()

        mockJournal.entries = [
            JournalEntry(
                id: UUID(), userId: userId, entryDate: now,
                mood: "good", energyLevel: 4, sleepHours: 7.5,
                sleepQuality: "good", waterLiters: 1.5, steps: 8000,
                trainingDone: true, trainingNotes: nil,
                mealsFollowed: 3, mealsTotal: 5,
                cravings: nil, symptoms: nil,
                freeText: nil, highlight: nil,
                tags: [], createdAt: now, updatedAt: now
            )
        ]

        let sut = makeSUT()
        await sut.loadDashboard(user: testUser)

        XCTAssertEqual(sut.waterLiters, 1.5)
    }

    func testLoadDashboardErrorShowsMessage() async {
        let testUser = makeTestUser(id: UUID())
        mockTask.shouldThrow = true

        let sut = makeSUT()
        await sut.loadDashboard(user: testUser)

        XCTAssertFalse(sut.isLoading)
        XCTAssertNotNil(sut.errorMessage)
    }

    // MARK: - Toggle Task

    func testToggleTaskOptimisticUI() {
        let sut = makeSUT()
        let now = Date()
        let taskId = UUID()
        sut.dailyTasks = [
            DailyTaskItem(id: taskId, userId: UUID(), taskDate: now, title: "Test", category: nil, isCompleted: false, completedAt: nil, sortOrder: 0, autoGenerated: false, source: "user", createdAt: now),
        ]

        sut.toggleDailyTask(sut.dailyTasks[0])
        XCTAssertTrue(sut.dailyTasks[0].isCompleted, "Toggle should flip completion state")
    }

    // MARK: - Last Coach Message

    func testLastCoachMessageFiltersAssistant() {
        let sut = makeSUT()
        let pid = UUID()
        sut.chatMessages = [
            CoachMessage(id: UUID(), profileId: pid, role: .user, channel: "app", messageText: "Hola", mediaType: nil, mediaUrl: nil, metadata: nil, expiresAt: nil, createdAt: Date().addingTimeInterval(-60)),
            CoachMessage(id: UUID(), profileId: pid, role: .assistant, channel: "app", messageText: "Buenos dias!", mediaType: nil, mediaUrl: nil, metadata: nil, expiresAt: nil, createdAt: Date()),
        ]

        let last = sut.lastCoachMessage
        XCTAssertNotNil(last)
        XCTAssertEqual(last?.role, .assistant)
        XCTAssertEqual(last?.messageText, "Buenos dias!")
    }

    func testLastCoachMessageNilWhenNoAssistant() {
        let sut = makeSUT()
        sut.chatMessages = [
            CoachMessage(id: UUID(), profileId: UUID(), role: .user, channel: "app", messageText: "Hola", mediaType: nil, mediaUrl: nil, metadata: nil, expiresAt: nil, createdAt: Date()),
        ]
        XCTAssertNil(sut.lastCoachMessage)
    }

    // MARK: - Helpers

    private func makeTestUser(id: UUID) -> AppUser {
        AppUser(
            id: id,
            authUserId: UUID(),
            coachProfileId: nil,
            firstName: "Test",
            lastName: "User",
            email: "test@test.com",
            phone: nil,
            avatarUrl: nil,
            sex: "male",
            dateOfBirth: nil,
            heightCm: 180,
            currentWeightKg: 80,
            goal: "Test goal",
            activityLevel: "moderate",
            foodAllergies: [],
            foodDislikes: [],
            dietType: nil,
            medicalConditions: [],
            timezone: "Europe/Madrid",
            locale: "es",
            notificationsEnabled: false,
            healthkitEnabled: false,
            onboardingCompleted: true,
            createdAt: Date(),
            updatedAt: Date()
        )
    }
}
