import XCTest
@testable import habitOS_mobile

final class ModelTests: XCTestCase {

    // MARK: - CoachMessage

    func testCoachMessageDecoding() throws {
        let json = """
        {
            "id": "AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA",
            "profile_id": "BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB",
            "role": "assistant",
            "channel": "app",
            "message_text": "Hola! Como va todo?",
            "created_at": "2026-01-15T10:30:00Z"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let message = try decoder.decode(CoachMessage.self, from: json)

        XCTAssertEqual(message.role, .assistant)
        XCTAssertEqual(message.channel, "app")
        XCTAssertEqual(message.messageText, "Hola! Como va todo?")
        XCTAssertEqual(message.profileId.uuidString.uppercased(), "BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB")
        XCTAssertNil(message.mediaType)
        XCTAssertNil(message.mediaUrl)
    }

    func testCoachMessageRoles() {
        XCTAssertEqual(MessageRole(rawValue: "user"), .user)
        XCTAssertEqual(MessageRole(rawValue: "assistant"), .assistant)
        XCTAssertEqual(MessageRole(rawValue: "system"), .system)
        XCTAssertNil(MessageRole(rawValue: "unknown"))
    }

    func testCoachMessageTextCompat() {
        let msg = CoachMessage(
            id: UUID(),
            profileId: UUID(),
            role: .user,
            channel: "app",
            messageText: "Test message",
            mediaType: nil,
            mediaUrl: nil,
            metadata: nil,
            expiresAt: nil,
            createdAt: Date()
        )
        // Backward-compat computed property
        XCTAssertEqual(msg.text, "Test message")
    }

    // MARK: - DailyTaskItem

    func testDailyTaskItemDecoding() throws {
        let json = """
        {
            "id": "CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCCCC",
            "user_id": "DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD",
            "task_date": "2026-01-15T00:00:00Z",
            "title": "Beber 2L de agua",
            "category": "hydration",
            "is_completed": false,
            "sort_order": 1,
            "auto_generated": true,
            "source": "plan",
            "created_at": "2026-01-15T00:00:00Z"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let task = try decoder.decode(DailyTaskItem.self, from: json)

        XCTAssertEqual(task.title, "Beber 2L de agua")
        XCTAssertEqual(task.category, "hydration")
        XCTAssertFalse(task.isCompleted)
        XCTAssertTrue(task.autoGenerated)
        XCTAssertEqual(task.source, "plan")
        XCTAssertNil(task.completedAt)
    }

    func testDailyTaskCategoryCompat() {
        // TaskCategory raw values should map from category strings
        XCTAssertEqual(DailyTaskItem.TaskCategory(rawValue: "nutrition"), .nutrition)
        XCTAssertEqual(DailyTaskItem.TaskCategory(rawValue: "hydration"), .hydration)
        XCTAssertEqual(DailyTaskItem.TaskCategory(rawValue: "activity"), .activity)
        XCTAssertNil(DailyTaskItem.TaskCategory(rawValue: "unknown"))
    }

    // MARK: - WeightLog

    func testWeightLogDecoding() throws {
        let json = """
        {
            "id": "EEEEEEEE-EEEE-EEEE-EEEE-EEEEEEEEEEEE",
            "user_id": "FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF",
            "weight_kg": 78.5,
            "body_fat_pct": 18.2,
            "source": "manual",
            "logged_at": "2026-01-15T08:00:00Z",
            "created_at": "2026-01-15T08:00:00Z"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let log = try decoder.decode(WeightLog.self, from: json)

        XCTAssertEqual(log.weightKg, 78.5)
        XCTAssertEqual(log.bodyFatPct, 18.2)
        XCTAssertNil(log.muscleMassKg)
        XCTAssertNil(log.waistCm)
        XCTAssertEqual(log.source, "manual")
    }

    // MARK: - CoachMemory

    func testCoachMemoryDecoding() throws {
        let json = """
        {
            "id": "11111111-1111-1111-1111-111111111111",
            "profile_id": "22222222-2222-2222-2222-222222222222",
            "fact_kind": "body",
            "title": "Peso",
            "fact_text": "Peso actual: 78 kg",
            "created_at": "2026-01-15T10:00:00Z"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let memory = try decoder.decode(CoachMemory.self, from: json)

        XCTAssertEqual(memory.factKind, "body")
        XCTAssertEqual(memory.title, "Peso")
        XCTAssertEqual(memory.factText, "Peso actual: 78 kg")
        // Backward-compat computed properties
        XCTAssertEqual(memory.category, "Cuerpo")
        XCTAssertEqual(memory.fact, "Peso actual: 78 kg")
    }

    func testCoachMemoryCategoryMapping() {
        let testCases: [(factKind: String, expected: String)] = [
            ("body", "Cuerpo"),
            ("goal", "Objetivos"),
            ("preference", "Preferencias"),
            ("restriction", "Restricciones"),
            ("allergy", "Restricciones"),
            ("context", "Historial"),
            ("schedule", "Historial"),
            ("habit", "Hábitos"),  // Note: Spanish special char
            ("medical", "Médico"),  // Note: Spanish special char
            ("something_new", "Otros"),
        ]

        for tc in testCases {
            let memory = CoachMemory(
                id: UUID(),
                profileId: UUID(),
                factKind: tc.factKind,
                title: "Test",
                factText: "Test fact",
                createdAt: Date()
            )
            XCTAssertEqual(memory.category, tc.expected, "fact_kind '\(tc.factKind)' should map to '\(tc.expected)'")
        }
    }

    // MARK: - JournalEntry

    func testJournalEntryDecoding() throws {
        let json = """
        {
            "id": "33333333-3333-3333-3333-333333333333",
            "user_id": "44444444-4444-4444-4444-444444444444",
            "entry_date": "2026-01-15T00:00:00Z",
            "mood": "good",
            "energy_level": 4,
            "water_liters": 1.8,
            "training_done": true,
            "training_notes": "Cardio 30 min",
            "tags": ["entrenamiento", "buena energia"],
            "created_at": "2026-01-15T20:00:00Z",
            "updated_at": "2026-01-15T20:00:00Z"
        }
        """.data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let entry = try decoder.decode(JournalEntry.self, from: json)

        XCTAssertEqual(entry.mood, "good")
        XCTAssertEqual(entry.energyLevel, 4)
        XCTAssertEqual(entry.waterLiters, 1.8)
        XCTAssertTrue(entry.trainingDone)
        XCTAssertEqual(entry.tags.count, 2)
    }
}
