import Foundation

/// Maps `coach_messages` table in Supabase
struct CoachMessage: Codable, Identifiable, Sendable {
    let id: UUID
    let profileId: UUID
    var role: MessageRole
    var channel: String // "telegram", "app", "web"
    var messageText: String
    var mediaType: String?
    var mediaUrl: String?
    var metadata: MessageMetadata?
    var expiresAt: Date?
    let createdAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case profileId = "profile_id"
        case role, channel
        case messageText = "message_text"
        case mediaType = "media_type"
        case mediaUrl = "media_url"
        case metadata
        case expiresAt = "expires_at"
        case createdAt = "created_at"
    }
}

enum MessageRole: String, Codable, Sendable {
    case user
    case assistant
    case system
}

struct MessageMetadata: Codable, Sendable {
    var eventType: String?
    var factKind: String?
    var importance: String?
    var readAt: Date?

    enum CodingKeys: String, CodingKey {
        case eventType = "event_type"
        case factKind = "fact_kind"
        case importance
        case readAt = "read_at"
    }
}

/// Maps `journal_entries` table in Supabase
struct JournalEntry: Codable, Identifiable, Sendable {
    let id: UUID
    let userId: UUID
    var entryDate: Date
    var mood: String? // great, good, neutral, bad, terrible
    var energyLevel: Int? // 1-5
    var sleepHours: Double?
    var sleepQuality: String? // great, good, fair, poor
    var waterLiters: Double?
    var steps: Int?
    var trainingDone: Bool
    var trainingNotes: String?
    var mealsFollowed: Int?
    var mealsTotal: Int?
    var cravings: String?
    var symptoms: String?
    var freeText: String?
    var highlight: String?
    var tags: [String]
    let createdAt: Date
    var updatedAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case entryDate = "entry_date"
        case mood
        case energyLevel = "energy_level"
        case sleepHours = "sleep_hours"
        case sleepQuality = "sleep_quality"
        case waterLiters = "water_liters"
        case steps
        case trainingDone = "training_done"
        case trainingNotes = "training_notes"
        case mealsFollowed = "meals_followed"
        case mealsTotal = "meals_total"
        case cravings, symptoms
        case freeText = "free_text"
        case highlight, tags
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

/// Maps `weight_logs` table in Supabase
struct WeightLog: Codable, Identifiable, Sendable {
    let id: UUID
    let userId: UUID
    var weightKg: Double
    var bodyFatPct: Double?
    var muscleMassKg: Double?
    var waistCm: Double?
    var hipCm: Double?
    var notes: String?
    var source: String // manual, healthkit, smart_scale
    var loggedAt: Date
    let createdAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case weightKg = "weight_kg"
        case bodyFatPct = "body_fat_pct"
        case muscleMassKg = "muscle_mass_kg"
        case waistCm = "waist_cm"
        case hipCm = "hip_cm"
        case notes, source
        case loggedAt = "logged_at"
        case createdAt = "created_at"
    }
}

/// Maps `daily_tasks` table in Supabase
struct DailyTaskItem: Codable, Identifiable, Sendable {
    let id: UUID
    let userId: UUID
    var taskDate: Date
    var title: String
    var category: String? // nutrition, hydration, activity, sleep, supplement, habit, other
    var isCompleted: Bool
    var completedAt: Date?
    var sortOrder: Int
    var autoGenerated: Bool
    var source: String // plan, coach, user, system
    let createdAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case taskDate = "task_date"
        case title
        case category
        case isCompleted = "is_completed"
        case completedAt = "completed_at"
        case sortOrder = "sort_order"
        case autoGenerated = "auto_generated"
        case source
        case createdAt = "created_at"
    }
}

/// Maps `shopping_lists` table in Supabase
struct ShoppingList: Codable, Identifiable, Sendable {
    let id: UUID
    let userId: UUID
    var planId: UUID?
    var weekStart: Date
    var items: [ShoppingItem]
    var autoGenerated: Bool
    let createdAt: Date
    var updatedAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case planId = "plan_id"
        case weekStart = "week_start"
        case items
        case autoGenerated = "auto_generated"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

struct ShoppingItem: Codable, Identifiable, Sendable {
    var id: UUID { UUID() }
    var name: String
    var quantity: String?
    var category: String?
    var checked: Bool

    enum CodingKeys: String, CodingKey {
        case name, quantity, category, checked
    }
}

/// Maps `food_scans` table
struct FoodScan: Codable, Identifiable, Sendable {
    let id: UUID
    let userId: UUID
    var barcode: String
    var productName: String?
    var brand: String?
    var nutriscoreGrade: String?
    var novaGroup: Int?
    var caloriesPer100g: Double?
    var allergens: [String]
    var isCompatible: Bool?
    var incompatibilityReason: String?
    var scannedAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case barcode
        case productName = "product_name"
        case brand
        case nutriscoreGrade = "nutriscore_grade"
        case novaGroup = "nova_group"
        case caloriesPer100g = "calories_per_100g"
        case allergens
        case isCompatible = "is_compatible"
        case incompatibilityReason = "incompatibility_reason"
        case scannedAt = "scanned_at"
    }
}

/// Maps `coach_profiles` table (read-only from app)
struct CoachProfile: Codable, Identifiable, Sendable {
    let id: UUID
    var displayName: String
    var coachName: String
    var coachMode: String
    var isActive: Bool

    enum CodingKeys: String, CodingKey {
        case id
        case displayName = "display_name"
        case coachName = "coach_name"
        case coachMode = "coach_mode"
        case isActive = "is_active"
    }
}

/// Maps `meal_logs` table
struct MealLog: Codable, Identifiable, Sendable {
    let id: UUID
    let userId: UUID
    var planId: UUID?
    var mealType: String // breakfast, mid_morning, lunch, snack, dinner, extra
    var actualDescription: String?
    var photoUrl: String?
    var followedPlan: Bool?
    var deviationReason: String?
    var loggedAt: Date
    let createdAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case planId = "plan_id"
        case mealType = "meal_type"
        case actualDescription = "actual_description"
        case photoUrl = "photo_url"
        case followedPlan = "followed_plan"
        case deviationReason = "deviation_reason"
        case loggedAt = "logged_at"
        case createdAt = "created_at"
    }
}
